version: "3"

vars:
  HUB_PACKAGE_DIR: node_modules/@giantcroissant-lunar/lunar-snake-hub
  NUKE_DIR_WIN: build\\nuke
  NUKE_DIR_UNIX: build/nuke
  GRAPH_HTML: .nuke/temp/execution-plan.html
  UNIFY_BUILD_TOOL: dotnet tool run unify-build --

tasks:
  hub:install-hooks:
    desc: Install pre-commit hooks from lunar-snake-hub into .git/hooks
    cmds:
      - cmd: node {{.HUB_PACKAGE_DIR}}/bin/hub-install-hooks.js

  hub:uninstall-hooks:
    desc: Uninstall pre-commit hooks and restore backups
    cmds:
      - cmd: node {{.HUB_PACKAGE_DIR}}/bin/hub-uninstall-hooks.js

  hub:symlink-agent:
    desc: Create .agent link to hub agent rules (for IDE agents)
    cmds:
      - cmd: |
          if not exist .agent (
            mklink /J .agent node_modules\@giantcroissant-lunar\lunar-snake-hub\.agent
          ) else (
            echo .agent already exists, skipping
          )
        platforms: [windows]
      - cmd: |
          if [ -L .agent ] || [ -e .agent ]; then
            echo ".agent already exists, skipping"
          else
            ln -s {{.HUB_PACKAGE_DIR}}/.agent .agent
          fi
        platforms: [linux, darwin]

  graph:
    desc: Generate NUKE target dependency graph (execution plan HTML)
    vars:
      TARGET: '{{default "PackProjects" .TARGET}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} {{.TARGET}} --plan'
      - cmd: echo Graph written to {{.GRAPH_HTML}}

  graph:open:
    desc: Generate + open the NUKE execution plan graph
    deps: [graph]
    cmds:
      - cmd: powershell -NoProfile -Command "Start-Process (Resolve-Path '{{.GRAPH_HTML}}')"
        platforms: [windows]
      - cmd: xdg-open '{{.GRAPH_HTML}}'
        platforms: [linux]
      - cmd: open '{{.GRAPH_HTML}}'
        platforms: [darwin]

  nuke:compile:
    desc: Run NUKE Compile (build)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} Compile --configuration {{.CONFIGURATION}}'

  nuke:pack-projects:
    desc: Run NUKE PackProjects (build NuGet packages)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} PackProjects --configuration {{.CONFIGURATION}}'

  nuke:publish-hosts:
    desc: Run NUKE PublishHosts (publish executables/hosts)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} PublishHosts --configuration {{.CONFIGURATION}}'

  nuke:publish-plugins:
    desc: Run NUKE PublishPlugins (publish plugins/runtime libraries)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} PublishPlugins --configuration {{.CONFIGURATION}}'

  nuke:publish-projects:
    desc: Run NUKE PublishProjects (publish explicit projects from build.config.json)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} PublishProjects --configuration {{.CONFIGURATION}}'

  nuke:sync-latest-artifacts:
    desc: Run NUKE SyncLatestArtifacts (sync build/_artifacts/{version} to build/_artifacts/latest)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - cmd: dotnet tool restore
      - cmd: '{{.UNIFY_BUILD_TOOL}} SyncLatestArtifacts --configuration {{.CONFIGURATION}}'

  dogfood:
    desc: Dogfood - Build unify-build using its own tooling and verify output
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - task: nuke:pack-projects
        vars:
          CONFIGURATION: '{{.CONFIGURATION}}'
      - cmd: powershell -NoProfile -ExecutionPolicy Bypass -File build/verify-dogfood.ps1
        platforms: [windows]

  dogfood:tool:
    desc: Dogfood - Build using the dotnet tool (requires tool to be installed)
    vars:
      CONFIGURATION: '{{default "Release" .CONFIGURATION}}'
    cmds:
      - echo "Building UnifyBuild.Tool package..."
      - dotnet pack -c {{.CONFIGURATION}} dotnet/src/UnifyBuild.Tool/UnifyBuild.Tool.csproj -o build/_artifacts/local/flat
      - echo "Installing local tool..."
      - dotnet tool install --local --add-source build/_artifacts/local/flat UnifyBuild.Tool || dotnet tool update --local --add-source build/_artifacts/local/flat UnifyBuild.Tool
      - echo "Running tool to build itself..."
      - dotnet unify-build PackProjects --configuration {{.CONFIGURATION}}
